name: Firebase Hosting Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter (master channel)
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web release
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLINIC_5E409 }}
          channelId: live
          projectId: clinic-5e409
