jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'   # Flutter version with Dart 3.8.1+
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      # Add your deploy steps here
